/*
  # Seed Geographically Diverse Directory Listings

  Adds 10 new healthcare organisations across different UK cities
  to make location-based search useful and demonstrative.

  New locations: Manchester, Birmingham, Leeds, Bristol, Edinburgh,
  Cardiff, Liverpool, Newcastle, Sheffield, Nottingham
*/

INSERT INTO directory_listings (name, slug, description, long_description, category_id, website, phone, city, region, postcode, cqc_rating, services, is_featured, is_verified) VALUES
  ('Northern Care Alliance', 'northern-care-alliance', 'Leading NHS group providing hospital and community services across Greater Manchester.', 'The Northern Care Alliance NHS Foundation Trust brings together Salford Royal and the Royal Oldham Hospital, along with community services across Salford, Oldham, Bury and Rochdale. Known for pioneering patient safety programmes and digital innovation in healthcare delivery.', (SELECT id FROM directory_categories WHERE slug = 'nhs-services'), 'https://www.northerncarealliance.nhs.uk', '0161 624 0420', 'Manchester', 'North West', 'M6 8HD', 'Good', ARRAY['Acute Care', 'Community Services', 'Rehabilitation', 'Specialist Surgery'], true, true),

  ('Birmingham Community Healthcare', 'birmingham-community-healthcare', 'Major community health provider serving over a million people across Birmingham and Solihull.', 'Birmingham Community Healthcare NHS Foundation Trust provides a wide range of community and specialist services to the people of Birmingham and Solihull. From district nursing and health visiting to rehabilitation and specialist dentistry, their dedicated teams deliver care closer to home.', (SELECT id FROM directory_categories WHERE slug = 'nhs-services'), 'https://www.bhamcommunity.nhs.uk', '0121 466 6000', 'Birmingham', 'West Midlands', 'B7 4BN', 'Good', ARRAY['Community Nursing', 'Rehabilitation', 'Specialist Dentistry', 'Health Visiting'], false, true),

  ('Leeds Care Group', 'leeds-care-group', 'Independent residential care provider operating quality homes across West Yorkshire.', 'Leeds Care Group manages a portfolio of residential and nursing care homes throughout West Yorkshire. Each home provides personalised care in welcoming environments, with dedicated activity coordinators, varied menus and strong community links. They focus on dignity, choice and independence for every resident.', (SELECT id FROM directory_categories WHERE slug = 'residential-care'), 'https://www.leedscaregroup.co.uk', '0113 245 6789', 'Leeds', 'Yorkshire', 'LS1 4AP', 'Good', ARRAY['Residential Care', 'Nursing Care', 'Dementia Care', 'Respite Care'], false, true),

  ('Bristol Home Care Services', 'bristol-home-care-services', 'Award-winning domiciliary care provider delivering compassionate home care across Bristol and South Gloucestershire.', 'Bristol Home Care Services has been providing exceptional home care across Bristol and surrounding areas for over 15 years. Their care workers are carefully matched to clients, building meaningful relationships that enhance wellbeing. Services range from 30-minute personal care visits to complex 24-hour live-in care packages.', (SELECT id FROM directory_categories WHERE slug = 'domiciliary-care'), 'https://www.bristolhomecare.co.uk', '0117 925 1234', 'Bristol', 'South West', 'BS1 3XD', 'Outstanding', ARRAY['Personal Care', 'Live-in Care', 'Companionship', 'Night Care', 'Medication Support'], true, true),

  ('Lothian Mental Health Services', 'lothian-mental-health', 'Comprehensive mental health and wellbeing services across Edinburgh and the Lothians.', 'Lothian Mental Health Services provides a full spectrum of mental health support, from community-based talking therapies to inpatient crisis care. Their multidisciplinary teams include psychiatrists, psychologists, mental health nurses and peer support workers, all committed to recovery-focused care.', (SELECT id FROM directory_categories WHERE slug = 'mental-health'), 'https://www.lothianmentalhealth.scot', '0131 537 6000', 'Edinburgh', 'Scotland', 'EH1 3EG', 'Good', ARRAY['Talking Therapies', 'Crisis Support', 'Community Mental Health', 'Addiction Services'], false, true),

  ('Valleys Care Wales', 'valleys-care-wales', 'Specialist learning disability support across South Wales with a focus on community inclusion.', 'Valleys Care Wales provides specialist supported living and day services for adults with learning disabilities across Cardiff, Swansea and the South Wales valleys. Their approach centres on enabling individuals to live fulfilling lives in their own communities, with personalised support that promotes independence and choice.', (SELECT id FROM directory_categories WHERE slug = 'learning-disabilities'), 'https://www.valleyscare.wales', '029 2034 5678', 'Cardiff', 'Wales', 'CF10 1EP', 'Good', ARRAY['Supported Living', 'Day Services', 'Community Inclusion', 'Employment Support'], false, true),

  ('Mersey Care Recruitment', 'mersey-care-recruitment', 'Specialist healthcare staffing agency covering Liverpool, Merseyside and North West England.', 'Mersey Care Recruitment specialises in placing healthcare professionals across hospitals, care homes and community settings throughout the North West. From temporary shifts to permanent placements, their experienced consultants understand the unique demands of the healthcare sector and maintain the highest standards of candidate vetting.', (SELECT id FROM directory_categories WHERE slug = 'recruitment-agencies'), 'https://www.merseycarerecruitment.co.uk', '0151 708 9012', 'Liverpool', 'North West', 'L2 3YL', '', ARRAY['Temporary Staffing', 'Permanent Recruitment', 'Nurse Recruitment', 'Care Worker Staffing'], false, true),

  ('Tyne Health Tech', 'tyne-health-tech', 'North East-based health technology company developing digital tools for care home management.', 'Tyne Health Tech builds intuitive software solutions for the social care sector, from digital care planning to medication management and family communication portals. Based in Newcastle, they work closely with care providers to develop tools that genuinely reduce administrative burden and improve care outcomes.', (SELECT id FROM directory_categories WHERE slug = 'technology-innovation'), 'https://www.tynehealthtech.co.uk', '0191 260 3456', 'Newcastle', 'North East', 'NE1 4ST', '', ARRAY['Digital Care Planning', 'Family Portal', 'Staff Scheduling', 'Compliance Reporting'], false, true),

  ('Sheffield Nursing Homes Group', 'sheffield-nursing-homes', 'Family-run nursing home group providing specialist care across South Yorkshire since 1998.', 'Sheffield Nursing Homes Group operates four purpose-built nursing homes across South Yorkshire, providing specialist nursing, residential and dementia care. As a family business with over 25 years of experience, they pride themselves on maintaining a warm, homely atmosphere while delivering clinical excellence. Each home has a dedicated activities programme and beautiful garden spaces.', (SELECT id FROM directory_categories WHERE slug = 'nursing-homes'), 'https://www.sheffieldnursinghomes.co.uk', '0114 276 7890', 'Sheffield', 'Yorkshire', 'S1 2GU', 'Good', ARRAY['Nursing Care', 'Dementia Care', 'Palliative Care', 'Residential Care'], false, true),

  ('Nottingham Home Support', 'nottingham-home-support', 'Trusted domiciliary care provider delivering tailored home care packages across Nottinghamshire.', 'Nottingham Home Support has been helping people remain independent in their own homes across Nottinghamshire for over a decade. Their services are built around individual needs and preferences, with consistent care teams who genuinely know and care about their clients. They specialise in supporting people with complex conditions including MS, Parkinson''s and stroke recovery.', (SELECT id FROM directory_categories WHERE slug = 'domiciliary-care'), 'https://www.nottinghamhomesupport.co.uk', '0115 947 3456', 'Nottingham', 'East Midlands', 'NG1 5AW', 'Good', ARRAY['Personal Care', 'Complex Care', 'Reablement', 'Overnight Care'], false, true)
ON CONFLICT (slug) DO NOTHING;